create table if not exists public.manga_translations (
  id bigint generated by default as identity primary key,
  series text not null check (series in ('manga-jp', 'manga-kana', 'manga-th')),
  chapter_number integer not null check (chapter_number > 0),
  page_number integer not null check (page_number > 0),
  line_number integer not null check (line_number > 0),
  romaji text not null default '',
  japanese text not null default '',
  meaning text not null default '',
  created_at timestamptz not null default now(),
  unique (series, chapter_number, page_number, line_number)
);

create index if not exists manga_translations_series_chapter_page_idx
  on public.manga_translations (series, chapter_number, page_number, line_number);

alter table public.manga_translations enable row level security;

drop policy if exists "Public can read manga translations" on public.manga_translations;
create policy "Public can read manga translations"
  on public.manga_translations for select to anon, authenticated
  using (true);

grant select on public.manga_translations to anon, authenticated;

insert into public.manga_translations
  (series, chapter_number, page_number, line_number, romaji, japanese, meaning)
values
  (
    'manga-kana', 1, 1, 1,
    'osananajimiomirumegakawatteshimatta',
    '幼なじみを見る目が変わってしまった',
    'มุมมองที่ฉันมีต่อเพื่อนสมัยเด็กเปลี่ยนไปแล้ว'
  ),
  (
    'manga-kana', 1, 2, 1,
    'iyada',
    'イヤだ (いやだ)',
    'ไม่ได้ / ไม่อะ ใช้ในการปฏิเสธ'
  )
on conflict (series, chapter_number, page_number, line_number)
do update set
  romaji = excluded.romaji,
  japanese = excluded.japanese,
  meaning = excluded.meaning;
