create table if not exists public.jlpt_vocabulary (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('N5', 'N4', 'N3', 'N2', 'N1')),
  word text not null,
  reading text not null default '',
  meaning text not null default '',
  created_at timestamptz not null default now(),
  unique (level, word, reading)
);

create table if not exists public.jlpt_kanji (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('N5', 'N4', 'N3', 'N2', 'N1')),
  character text not null,
  readings_on text[] not null default '{}',
  readings_kun text[] not null default '{}',
  meaning text not null default '',
  created_at timestamptz not null default now(),
  unique (level, character)
);

create table if not exists public.jlpt_grammar (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('N5', 'N4', 'N3', 'N2', 'N1')),
  pattern text not null,
  reading text not null default '',
  meaning text not null default '',
  explanation text not null default '',
  example_jp text not null default '',
  example_th text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (level, pattern)
);

create table if not exists public.manga_translations (
  id bigint generated by default as identity primary key,
  series text not null check (series in ('manga-jp', 'manga-kana', 'manga-th')),
  chapter_number integer not null check (chapter_number > 0),
  page_number integer not null check (page_number > 0),
  line_number integer not null check (line_number > 0),
  romaji text not null default '',
  japanese text not null default '',
  meaning text not null default '',
  created_at timestamptz not null default now(),
  unique (series, chapter_number, page_number, line_number)
);

create index if not exists jlpt_vocabulary_level_idx
  on public.jlpt_vocabulary (level, word);
create index if not exists jlpt_kanji_level_idx
  on public.jlpt_kanji (level, character);
create index if not exists jlpt_grammar_level_order_idx
  on public.jlpt_grammar (level, sort_order, id);
create index if not exists manga_translations_series_chapter_page_idx
  on public.manga_translations (series, chapter_number, page_number, line_number);

alter table public.jlpt_vocabulary enable row level security;
alter table public.jlpt_kanji enable row level security;
alter table public.jlpt_grammar enable row level security;
alter table public.manga_translations enable row level security;

drop policy if exists "Public can read JLPT vocabulary" on public.jlpt_vocabulary;
create policy "Public can read JLPT vocabulary"
  on public.jlpt_vocabulary for select to anon, authenticated
  using (true);

drop policy if exists "Public can read JLPT kanji" on public.jlpt_kanji;
create policy "Public can read JLPT kanji"
  on public.jlpt_kanji for select to anon, authenticated
  using (true);

drop policy if exists "Public can read JLPT grammar" on public.jlpt_grammar;
create policy "Public can read JLPT grammar"
  on public.jlpt_grammar for select to anon, authenticated
  using (true);

drop policy if exists "Public can read manga translations" on public.manga_translations;
create policy "Public can read manga translations"
  on public.manga_translations for select to anon, authenticated
  using (true);

grant select on public.jlpt_vocabulary to anon, authenticated;
grant select on public.jlpt_kanji to anon, authenticated;
grant select on public.jlpt_grammar to anon, authenticated;
grant select on public.manga_translations to anon, authenticated;

insert into public.manga_translations
  (series, chapter_number, page_number, line_number, romaji, japanese, meaning)
values
  (
    'manga-kana', 1, 1, 1,
    'osananajimiomirumegakawatteshimatta',
    '幼なじみを見る目が変わってしまった',
    'มุมมองที่ฉันมีต่อเพื่อนสมัยเด็กเปลี่ยนไปแล้ว'
  ),
  (
    'manga-kana', 1, 2, 1,
    'iyada',
    'イヤだ (いやだ)',
    'ไม่ได้ / ไม่อะ ใช้ในการปฏิเสธ'
  )
on conflict (series, chapter_number, page_number, line_number)
do update set
  romaji = excluded.romaji,
  japanese = excluded.japanese,
  meaning = excluded.meaning;
